/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package system.admin;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author Acer 2021
 */
public class topupPanelAction extends javax.swing.JPanel {

    /**
     * Creates new form topupPanelACtion
     */
    public topupPanelAction() {
        initComponents();
    }

    public void initTopupEvent(TableActionEvent topupevent, int row) {
        cmdApprove.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                topupevent.onApprove(row);
            }
        });
        cmdDecline.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                topupevent.onDecline(row);
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmdDecline = new system.admin.ActionButton();
        cmdApprove = new system.admin.ActionButton();

        cmdDecline.setIcon(new javax.swing.ImageIcon(getClass().getResource("/decline.png"))); // NOI18N
        cmdDecline.setMaximumSize(new java.awt.Dimension(30, 30));
        cmdDecline.setPreferredSize(new java.awt.Dimension(30, 30));
        cmdDecline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdDeclineActionPerformed(evt);
            }
        });

        cmdApprove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/check.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cmdApprove, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdDecline, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmdDecline, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdApprove, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmdDeclineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdDeclineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdDeclineActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private system.admin.ActionButton cmdApprove;
    private system.admin.ActionButton cmdDecline;
    // End of variables declaration//GEN-END:variables
}
