/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package system.admin;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.DefaultListModel;

/**
 *
 * @author alvis
 */
public class TransactionPanel extends javax.swing.JPanel {

    public void loadUserTransaction(String userID) {
        System.out.println("Loading transactions for user: " + userID);

        // Get the user's name from users.txt
        String userName = getUserName(userID);
        if (userName == null) {
            System.out.println("User not found in users.txt!");
            return;
        }

        try (BufferedReader br = new BufferedReader(new FileReader("userTopup.txt"))) {
            String line;
            while ((line = br.readLine()) != null) {
                System.out.println("Checking line: " + line);
                String[] details = line.split(";");

                if (details.length >= 4 && details[0].equals(userID)) {
                    System.out.println("Match found!");

                    String paymentMethod = details[1];
                    double amount = Double.parseDouble(details[2]);
                    double balance = Double.parseDouble(details[3]);

                    // Update UI with user details
                    setName.setText(userName); // Set the real name
                    setPayment.setText(paymentMethod);
                    setAmount.setText("RM " + amount);
                    setBalance.setText("RM " + balance);

                    this.setVisible(true);
                    break; // Stop after the first match
                }
            }
        } catch (IOException e) {
            System.out.println("Error reading userTopup.txt: " + e.getMessage());
        }
    }

    private String getUserName(String userID) {
        try (BufferedReader br = new BufferedReader(new FileReader("users.txt"))) {
            String line;
            while ((line = br.readLine()) != null) {
                String[] details = line.split(";");

                if (details.length >= 2 && details[0].equals(userID)) {
                    return details[1]; // Return the name in column [1]
                }
            }
        } catch (IOException e) {
            System.out.println("Error reading users.txt: " + e.getMessage());
        }
        return null; // Return null if user not found
    }

    /**
     * Creates new form TransactionPanel
     */
    public TransactionPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setPayment = new javax.swing.JLabel();
        setAmount = new javax.swing.JLabel();
        setBalance = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        setName = new javax.swing.JLabel();

        setPayment.setText("setPayment");

        setAmount.setText("setAmount");

        setBalance.setText("setBalance");

        jLabel1.setText("Name:");

        jLabel2.setText("Payment Method:");

        jLabel3.setText("Amount:");

        jLabel4.setText("Total balance:");

        setName.setText("setName");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(setPayment)
                            .addComponent(setName))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(setAmount)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(setBalance)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(setName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(setPayment))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(setAmount)
                    .addComponent(setBalance))
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel setAmount;
    private javax.swing.JLabel setBalance;
    private javax.swing.JLabel setName;
    private javax.swing.JLabel setPayment;
    // End of variables declaration//GEN-END:variables
}
